crud/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name ='crud'
urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('crud/', views.ProductListView.as_view(), name="list"),
    path('crud/create/', views.ProductCreateView.as_view(), name="create"),
    path('crud/detail/<int:pk>', views.ProductDetailView.as_view(), name="detail"),
    # path('crud/edit/<int:pk>', views.ProductUpdateView.as_view(), name="edit"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from crud import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Top.as_view()),
    path('crud/', views.ProductListView.as_view(), name="list"),
    path('crud/new/', views.ProductCreateView.as_view(), name="create"),
    path('crud/detail/<int:pk>', views.ProductDetailView.as_view(), name="detail"),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls')),
]

crud/models.py
from django.db import models

class Category(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name

class Product(models.Model):
  name = models.CharField(max_length=200)
  explanation = models.TextField()
  price = models.PositiveIntegerField(null=True, blank=True)
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  img = models.ImageField(blank=True, default='noImage.png')

  def __str__(self):
    return self.name

crud/views.py
from django.shortcuts import render
from django.views.generic import  ListView, DetailView, TemplateView
from django.views.generic.edit import  CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Product

class TopView(TemplateView):
  template_name = 'top.html'

class ProductCreateView(CreateView):
  model = Product
  fields = '__all__'
  success_url = reverse_lazy('list') 

class ProductListView(ListView):
  template_name = 'list.html'
  model = Product
  paginate_by = 4

class ProductDetailView(DetailView):
  model = Product
  fileds = '__all__'
  success_url = reverse_lazy('list')

# class ProductUpdateView(UpdateView):
#   model = Product
#   fileds = '__all__'
#   template_name_suffix = '_updete_form.html'
#   success_url = reverse_lazy('crud_list')

myproject/crud/views.py
from django.shortcuts import render
from django.views.generic import  ListView, DetailView, TemplateView, CreateView
from django.urls import reverse_lazy
from .models import Product

class Top(TemplateView):
  template_name = 'top.html'

class ProductCreateView(CreateView):
  template_name = "create.html"
  success_url = reverse_lazy('list') 

class ProductListView(ListView):
  model = Product
  template_name ="list.html"
  paginate_by = 4

class ProductDetailView(DetailView):
  model = Product
  filed = '__All__'

crud/templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>

</html>

crud/templates/crud/product_detail.html
{% extends 'base.html' %}

{% block title %}詳細ページ{% endblock %}

{% block content %}    
<h1>詳細ページ</h1>
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>本文</th>
      <th>価格</th>
      <th>カテゴリー</th>
      <th>画像</th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <td>{{ object.name }}</td>
      <td>{{ object.explanation}}</td>
      <td>{{ object.price }}</td>
      <td>{{ object.category }}</td>
      <td><img class="img-thumbnail border border-primary" src="{{ object.img.url }}"></td>
    </tr>
  </tbody>
</table>

<br>
<a href="{% url 'crud:list' %}">戻る</a>
{% endblock %}

crud/templates/crud/product_form.html
{% extends 'base.html' %}

{% block title %}新規作成{% endblock %}

{% block content %}    
<h1>新規作成</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table table-striped">
  {{ form.as_table }}
  </table>
  <br>
  <a class="btn btn-secondary" href="{% url 'crud:list' %}">戻る</a>
  <input type="submit" class="btn btn-success" value="登録">
</form>
{% endblock %}

crud/templates/crud/product_list.html
{% extends 'base.html' %}

{% block title %}一覧ページ{% endblock %}

{% block content %}    
<h1>一覧ページ </h1>
<a class="btn btn-light" href="{% url 'crud:create' %}">新規作成</a>
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>商品名</th>
      <th>カテゴリー</th>
      <th>アクション</th>
    </tr>
  </thead>
  <tbody>
    {% for product in object_list %}
    <tr>
      <td>{{ product.name }}</td>
      <td>{{ product.category }}</td>
      <td>
        <a class="btn btn-primary" href='{% url "crud:detail" pk=product.pk %}'>詳細</a>
      </td>
    </tr>
    {% endfor %}
</table>
  
  <!-- ページネーション -->
{# ページの表示 現在/総ページ #}

{{ page_obj.number }} / {{page_obj.paginator.num_pages }}ぺージ<br>

{# 前のページ&先頭遷移設定 #}
{% if page_obj.has_previous %}
<a href="?page=1">&laquo; 先頭</a>
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{# 次のページ&最後尾遷移設定 #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
<a href="?page={{ page_obj.paginator.num.pages }}">最後へ &laquo;</a>
{% endif %}
{% endblock %}

crud/templates/crud/product_update_form.html
{% extends 'base.html' %}

{% block title %}編集ページ{% endblock %}

{% block content %}    
<h1>編集</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="table table-striped">
  {{ form.as_table }}
  </table>
  <br>
  <a class="btn btn-secondary" href="{% url 'crud:list' %}">戻る</a>
  <input type="submit" class="btn btn-success" value="編集">
</form>
{% endblock %}

crud/templates/top.html
{% extends 'base.html' %}

{% block content %}
<h1>564789</h1>
<a class="fs-1 position-absolute top-50 start-50 translate-middle"href="{% url 'crud:list' %}">list</a>
{% endblock %}

myproject/crud/templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    {% endblock%}
  </body>

</html>

myproject/crud/templates/crud/product_create.html
{% extends 'base.html' %}

{% block title %}新規作成{% endblock %}

{% block content %}
<h1>新規作成</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <br>
  <a href="{% url 'list' %}">戻る</a>
  <input type="submit" class="btn btn-info" value="登録">
</form>
{% endblock %}

myproject/crud/templates/crud/product_detail.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>商品詳細</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <h1>商品詳細</h1>
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>商品名</th>
          <th>価格</th>
          <th>カテゴリー</th>
          <th>画像</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ object.name }}</td>
          <td>{{ object.explanation}}</td>
          <td>{{ object.price }}</td>
          <td>{{ object.category }}</td>
          <td>{{ object.img }}</td>
        </tr>
      </tbody>
    </table>

    <br>
    <a href="{% url 'list' %}">戻る</a>

  </body>
</html>

myproject/crud/templates/crud/product_list.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>商品一覧</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <h1>商品一覧</h1>
    <a class="btn btn-primary" href="{% url 'new' %}">新規作成</a>
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>商品名</th>
          <th>アクション</th>
        </tr>
      </thead>
      <tbody>
        {% for product in object_list %}
        <tr>
          <td>{{ product.name }}</td>
          <td>
            <button class="btn btn-primary" onclick="location.href='{% url 'detail' pk=product.pk %}'">詳細</button>
          </td>
        </tr>
        {% endfor %}
    </table>
     
      <!-- ページネーション -->
    {# ページの表示 現在/総ページ #}
    
    {{ page_obj.number }} / {{page_obj.paginator.num_pages }}ぺージ<br>

    {# 前のページ&先頭遷移設定 #}
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; 先頭</a>
    <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
    {% endif %}

    {# 次のページ&最後尾遷移設定 #}
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">次へ</a>
    <a href="?page={{ page_obj.paginator.num.pages }}">最後へ &laquo;</a>
    {% endif %}
  </body>
</html>